apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-demo
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: '2023-06-14T04:53:17Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: kube-prometheus-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.5.3
    helm.sh/chart: grafana-6.57.1
    release: kube-prometheus-demo
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          .: {}
          f:endpoints: {}
          f:jobLabel: {}
          f:namespaceSelector:
            .: {}
            f:matchNames: {}
          f:selector: {}
      manager: helm
      operation: Update
      time: '2023-06-14T04:53:17Z'
  name: kube-prometheus-demo-grafana
  namespace: monitoring
  resourceVersion: '770'
  uid: 2c1616fc-2662-4cad-a6bd-96d7b03f507c
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http-web
      scheme: http
      scrapeTimeout: 30s
  jobLabel: kube-prometheus-demo
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-demo
      app.kubernetes.io/name: grafana
